FROM python:3.11-slim

RUN apt-get update && apt-get install -y git postgresql-client && rm -rf /var/lib/apt/lists/*

WORKDIR /scripts

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
