version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: exploitpulse
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_user
      - pg_password
      - nvd_api_key
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  exploitpulse_importer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - /opt/exploitpulse/etl/secrets:/run/secrets:ro
      - /opt/exploitpulse/etl-data:/etl-data
      - /opt/exploitpulse/etl/secrets/packetstorm_auth:/etl/secrets/packetstorm_auth:ro
      - /opt/exploitpulse/etl/secrets/cert_cc_api_key:/opt/exploitpulse/etl/secrets/cert_cc_api_key:ro
    working_dir: /scripts
    depends_on:
      - db
    environment:
      PGHOST: db
      PGDATABASE: exploitpulse
      PYTHONPATH: /scripts/etl
    command: ["/wait-for-it.sh", "db:5432", "--"]

  # Add additional VulnCheck importers as needed
  # vulncheck_exploited_importer:
  #   ...

  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=en,fr,de,es,it,ru,zh

volumes:
  pgdata:

secrets:
  pg_user:
    file: ../etl/secrets/pg_user
  pg_password:
    file: ../etl/secrets/pg_password
  nvd_api_key:
    file: ../etl/secrets/nvd_api_key
  vulncheck_api_key:
    file: ../etl/secrets/vulncheck_api_key
